name: CI

variables:
  FUNCTION_NAME: "torger-function-app"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build step"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test step"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Azure..."
      - run: func azure functionapp publish $FUNCTION_NAME
      - run: echo "Deployed to Azure successfully"
